#Minecraft server properties
#Generated automatically
spawn-protection=16
max-tick-time=60000
query.port=25565
level-seed=
enable-rcon=false
enable-command-block=false
gamemode=survival
enable-query=false
player-idle-timeout=0
difficulty=easy
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=minecraft\:normal
hardcore=false
online-mode=false
allow-flight=false
resource-pack=
max-players=20
motd=\u00a76Inception \u00a7cMinecraft \u00a72Server
server-port=25565
